apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: rabbitmq
spec:
  ports:
  - name: http
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: http-mqtt
    port: 15675
    protocol: TCP
    targetPort: 15675
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    run: rabbitmq
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rabbitmq
  name: rabbitmq
spec:
  containers:
  - image: settlemint/rabbitmq-mqtt
    name: rabbitmq
    ports:
    - name: http
      containerPort: 15672
    - name: http-mqtt
      containerPort: 15675
    - name: amqp
      containerPort: 5672
    - name: mqtt
      containerPort: 1883
    env:
      - name: RABBITMQ_VM_MEMORY_HIGH_WATERMARK
        value: "0.9" 
      - name: RABBITMQ_DEFAULT_VHOST
        value: / 
      - name: RABBITMQ_USER
        value: guest
      - name: RABBITMQ_PASSWORD
        value: guest
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
